In [1]:
from marubatsu import Marubatsu, ListBoard, List1dBoard, ArrayBoard, NpBoard, NpIntBoard, NpBoolBoard, BitBoard, BitBoard3x3, TwoBitBoard3x3
from util import playout

for boardclass in [ListBoard, List1dBoard, ArrayBoard, NpBoard, NpIntBoard, NpBoolBoard, BitBoard, BitBoard3x3, TwoBitBoard3x3]:
    for count_linemark in [False, True]:
        if boardclass in [BitBoard3x3, TwoBitBoard3x3] and count_linemark == True:
            continue
        print(f"boardclass = {boardclass.__name__} count_linemark = {count_linemark}")
        mb = Marubatsu(boardclass=boardclass, count_linemark=count_linemark)
        retval = playout(mb, pnum=100000000, timelimit=1)
        print(f"playout count = {retval['count']}")

boardclass = ListBoard count_linemark = False
playout count = 16625
boardclass = ListBoard count_linemark = True
playout count = 13843
boardclass = List1dBoard count_linemark = False
playout count = 22207
boardclass = List1dBoard count_linemark = True
playout count = 15236
boardclass = ArrayBoard count_linemark = False
playout count = 21743
boardclass = ArrayBoard count_linemark = True
playout count = 15985
boardclass = NpBoard count_linemark = False
playout count = 10221
boardclass = NpBoard count_linemark = True
playout count = 10634
boardclass = NpIntBoard count_linemark = False
playout count = 12227
boardclass = NpIntBoard count_linemark = True
playout count = 12647
boardclass = NpBoolBoard count_linemark = False
playout count = 12390
boardclass = NpBoolBoard count_linemark = True
playout count = 10252
boardclass = BitBoard count_linemark = False
playout count = 13613
boardclass = BitBoard count_linemark = True
playout count = 10664
boardclass = BitBoard3x3 count_linemark = False
p

In [2]:
import random

random.seed(0)
mb = Marubatsu()
retval = playout(mb, 10000)
move = mb.board.xy_to_move(0, 0)
data = retval["result"][move]
print(f"(0, 0) o {data[mb.CIRCLE]} x {data[mb.CROSS]} draw {data[mb.DRAW]}")

(0, 0) o 710 x 298 draw 156


In [3]:
from copy import deepcopy

mb = Marubatsu()
%timeit playout(mb, 100)

3.85 ms ± 11.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%%timeit
for _ in range(100):
    deepcopy(mb)

2.12 ms ± 11.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
from time import perf_counter
from copy import deepcopy

def playout(self, pnum, timelimit=None):
    if timelimit is not None:   
        starttime = perf_counter()
        timelimit_pc = starttime + timelimit        
    result = {}
    for move in self.calc_legal_moves():
        result[move] = {
            self.CIRCLE: 0,
            self.CROSS: 0,
            self.DRAW: 0,
        }
    count = 0
    board = deepcopy(self.board)
    for _ in range(pnum):
        if timelimit is not None and perf_counter() > timelimit_pc:
            break
        turn = self.turn
        move_count = self.move_count
        status = self.status
        firstmove = None
        while status == self.PLAYING:
            move = random.choice(self.calc_legal_moves())
            if firstmove is None:
                firstmove = move
            self.board.setmark_by_move(move, turn)
            last_turn = turn
            turn = self.CROSS if turn == self.CIRCLE else self.CIRCLE
            move_count += 1
            status = self.board.judge(last_turn, move, move_count)
        self.board = deepcopy(board)
        result[firstmove][status] += 1
        count += 1
    return {
        "result": result,
        "count": count,
    }
    
Marubatsu.playout = playout

In [6]:
random.seed(0)
retval = mb.playout(10000)
move = mb.board.xy_to_move(0, 0)
data = retval["result"][move]
print(f"(0, 0) o {data[mb.CIRCLE]} x {data[mb.CROSS]} draw {data[mb.DRAW]}")

(0, 0) o 710 x 298 draw 156


In [7]:
for boardclass in [ListBoard, List1dBoard, ArrayBoard, NpBoard, NpIntBoard, NpBoolBoard, BitBoard, BitBoard3x3, TwoBitBoard3x3]:
    for count_linemark in [False, True]:
        if boardclass in [BitBoard3x3, TwoBitBoard3x3] and count_linemark == True:
            continue
        print(f"boardclass = {boardclass.__name__} count_linemark = {count_linemark}")
        mb = Marubatsu(boardclass=boardclass, count_linemark=count_linemark)
        retval = mb.playout(pnum=100000000, timelimit=1)
        print(f"playout count = {retval['count']}")

boardclass = ListBoard count_linemark = False
playout count = 28327
boardclass = ListBoard count_linemark = True
playout count = 20445
boardclass = List1dBoard count_linemark = False
playout count = 39620
boardclass = List1dBoard count_linemark = True
playout count = 23251
boardclass = ArrayBoard count_linemark = False
playout count = 41177
boardclass = ArrayBoard count_linemark = True
playout count = 23935
boardclass = NpBoard count_linemark = False
playout count = 14189
boardclass = NpBoard count_linemark = True
playout count = 14417
boardclass = NpIntBoard count_linemark = False
playout count = 18041
boardclass = NpIntBoard count_linemark = True
playout count = 18303
boardclass = NpBoolBoard count_linemark = False
playout count = 18656
boardclass = NpBoolBoard count_linemark = True
playout count = 13625
boardclass = BitBoard count_linemark = False
playout count = 19077
boardclass = BitBoard count_linemark = True
playout count = 13415
boardclass = BitBoard3x3 count_linemark = False
p

In [8]:
from marubatsu import Board
from abc import ABCMeta, abstractmethod

@abstractmethod
def save(self):
    pass

Board.save = save

@abstractmethod
def load(self, data):
    pass

Board.load = load

In [9]:
from copy import copy

a = ["o", "x", ".", ".", "x", "o", "o", ".", "x"]
print("list の copy メソッドによるコピー")
print(a.copy())
print("スライス表記 [:] によるコピー")
print(a[:])
print("copy モジュールの copy による浅いコピー")
print(copy(a))

list の copy メソッドによるコピー
['o', 'x', '.', '.', 'x', 'o', 'o', '.', 'x']
スライス表記 [:] によるコピー
['o', 'x', '.', '.', 'x', 'o', 'o', '.', 'x']
copy モジュールの copy による浅いコピー
['o', 'x', '.', '.', 'x', 'o', 'o', '.', 'x']


In [10]:
print("list の copy メソッドによるコピー")
%timeit a.copy()
print("スライス表記 [:] によるコピー")
%timeit a[:]
print("copy モジュールの copy による浅いコピー")
%timeit copy(a)

list の copy メソッドによるコピー
64.4 ns ± 0.377 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
スライス表記 [:] によるコピー
83.4 ns ± 1.13 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
copy モジュールの copy による浅いコピー
149 ns ± 1.01 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [11]:
import numpy as np
import pickle

mb = Marubatsu(boardclass=ListBoard)
mb.cmove(0, 0)
mb.cmove(1, 0)
mb.cmove(2, 1)
print(mb)
print("deepcopy")
board = deepcopy(mb.board)
mb.board = deepcopy(board)
print(mb)
print("ndarray")
board = np.array(mb.board)
mb.board = board.tolist()
print(mb)
print("pickle")
board = pickle.dumps(mb.board)
mb.board = pickle.loads(board)
print(mb)

Turn x
ox.
..O
...

deepcopy
Turn x
ox.
..O
...

ndarray
Turn x
ox.
..O
...

pickle
Turn x
ox.
..O
...



In [12]:
print("deepcopy")
%timeit deepcopy(mb.board)
board = deepcopy(mb.board)
%timeit deepcopy(board)
print("ndarray")
%timeit np.array(mb.board)
board = np.array(mb.board)
%timeit board.tolist()
print("pickle")
%timeit pickle.dumps(mb.board)
board = pickle.dumps(mb.board)
%timeit mb.board = pickle.loads(board)

deepcopy
11.1 μs ± 71.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
11 μs ± 63.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
ndarray
373 ns ± 2.09 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
50.6 ns ± 0.379 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
pickle
2.88 μs ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.36 μs ± 30 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
print("list の copy メソッドによるコピー")
%timeit a.copy()
print("スライス表記 [:] によるコピー")
%timeit a[:]
print("copy モジュールの copy による浅いコピー")
%timeit copy(a)
print("ndarray に変換後 tolist メソッドによる変換")
%timeit np.array(a)
b = np.array(a)
%timeit b.tolist()
print("pickle による変換と復元")
%timeit pickle.dumps(a)
c = pickle.dumps(a)
%timeit pickle.loads(c)

list の copy メソッドによるコピー
64.4 ns ± 0.708 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
スライス表記 [:] によるコピー
82.3 ns ± 0.127 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
copy モジュールの copy による浅いコピー
148 ns ± 0.716 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
ndarray に変換後 tolist メソッドによる変換
1.69 μs ± 10 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
160 ns ± 2.08 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
pickle による変換と復元
1.15 μs ± 5.36 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
505 ns ± 3.76 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
from array import array

a = array("w", ["o", "x", ".", ".", "x", "o", "o", ".", "x"])
print(a)
print("スライス表記 [:] によるコピー")
print(a[:])
print("copy モジュールの copy による浅いコピー")
print(copy(a))

array('w', 'ox..xoo.x')
スライス表記 [:] によるコピー
array('w', 'ox..xoo.x')
copy モジュールの copy による浅いコピー
array('w', 'ox..xoo.x')


In [15]:
print("スライス表記 [:] によるコピー")
%timeit a[:]
print("copy モジュールの copy による浅いコピー")
%timeit copy(a)

スライス表記 [:] によるコピー
91.1 ns ± 0.175 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
copy モジュールの copy による浅いコピー
234 ns ± 3.08 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
a = np.array([["o", "x", "."], [".", "x", "o"], ["o", ".", "x"]])
print("ndarray の copy メソッドによるコピー")
print(a.copy())
print("copy モジュールの copy によるコピー")
print(copy(a))

ndarray の copy メソッドによるコピー
[['o' 'x' '.']
 ['.' 'x' 'o']
 ['o' '.' 'x']]
copy モジュールの copy によるコピー
[['o' 'x' '.']
 ['.' 'x' 'o']
 ['o' '.' 'x']]


In [17]:
print("ndarray の copy メソッドによるコピー")
%timeit a.copy()
print("copy モジュールの copy によるコピー")
%timeit copy(a)

ndarray の copy メソッドによるコピー
318 ns ± 4.67 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
copy モジュールの copy によるコピー
495 ns ± 5.27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
print(a[0][0])
b = copy(a)
b[0][0] = "x"
print(a[0][0])
print(b[0][0])

o
o
x


In [19]:
a = np.array([1, 2, 3])
print(a)
b = a[:]
print(b)
b[0] = 5
print(a)
print(b)

[1 2 3]
[1 2 3]
[5 2 3]
[5 2 3]


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
b = a[:2, :2]
print(b)
b[0][0] = 5
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[5 2 3]
 [4 5 6]
 [7 8 9]]
[[5 2]
 [4 5]]


In [21]:
mb = Marubatsu(boardclass=ListBoard, count_linemark=True)
mb.cmove(0, 0)
mb.cmove(1, 1)
print(mb.board.rowcount)
circlelist = mb.board.rowcount[mb.CIRCLE].copy()
crosslist = mb.board.rowcount[mb.CROSS].copy()
mb.board.rowcount = {
    mb.CIRCLE: circlelist.copy(),
    mb.CROSS: crosslist.copy(),
}
print(mb.board.rowcount)

{'o': [1, 0, 0], 'x': [0, 1, 0]}
{'o': [1, 0, 0], 'x': [0, 1, 0]}


In [22]:
%timeit deepcopy(mb.board.rowcount)

4.74 μs ± 26.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
%%timeit 
# データのコピー
circlelist = mb.board.rowcount[mb.CIRCLE].copy()
crosslist = mb.board.rowcount[mb.CROSS].copy()

190 ns ± 1.95 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [24]:
%%timeit
# データの復元
mb.board.rowcount = {
    mb.CIRCLE: circlelist.copy(),
    mb.CROSS: crosslist.copy(),
}

227 ns ± 0.993 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [25]:
def save_count(self):
    return (self.rowcount[self.CIRCLE].copy(), self.rowcount[self.CROSS].copy(),
            self.colcount[self.CIRCLE].copy(), self.rowcount[self.CROSS].copy(),
            self.diacount[self.CIRCLE].copy(), self.rowcount[self.CROSS].copy())
    
ListBoard.save_count = save_count

def load_count(self, data):
    self.rowcount = {
        self.CIRCLE: data[0].copy(),
        self.CROSS: data[1].copy(),
    }
    self.colcount = {
        self.CIRCLE: data[2].copy(),
        self.CROSS: data[3].copy(),
    }
    self.diacount = {
        self.CIRCLE: data[4].copy(),
        self.CROSS: data[5].copy(),
    }
    
ListBoard.load_count = load_count

In [26]:
def save(self):
    board = np.array(self.board)
    if self.count_linemark:
        return board, self.save_count()
    else:
        return board
    
ListBoard.save = save

def load(self, data):
    if self.count_linemark:
        self.board = data[0].tolist()
        self.load_count(data[1])
    else:
        self.board = data.tolist()
        
ListBoard.load = load

In [27]:
def save(self):
    board = self.board.copy()
    if self.count_linemark:
        return board, self.save_count()
    else:
        return board
    
List1dBoard.save = save

def load(self, data):
    if self.count_linemark:
        self.board = data[0].copy()
        self.load_count(data[1])
    else:
        self.board = data.copy()
        
List1dBoard.load = load

In [28]:
def save(self):
    board = self.board[:]
    if self.count_linemark:
        return board, self.save_count()
    else:
        return board
    
ArrayBoard.save = save

def load(self, data):
    if self.count_linemark:
        self.board = data[0][:]
        self.load_count(data[1])
    else:
        self.board = data[:]
        
ArrayBoard.load = load

In [29]:
def save(self):
    board = self.board.copy()
    if self.count_linemark:
        return board, self.save_count()
    else:
        return board
    
NpBoard.save = save

def load(self, data):
    if self.count_linemark:
        self.board = data[0].copy()
        self.load_count(data[1])
    else:
        self.board = data.copy()
        
NpBoard.load = load

In [30]:
BitBoard.save_count = save_count
BitBoard.load_count = load_count

def save(self):
    board = self.board.copy()
    if self.count_linemark:
        return board, self.save_count()
    else:
        return board
    
BitBoard.save = save

def load(self, data):
    if self.count_linemark:
        self.board = data[0].copy()
        self.load_count(data[1])
    else:
        self.board = data.copy()
        
BitBoard.load = load

In [31]:
def save(self):
    return self.board.copy()
    
BitBoard3x3.save = save

def load(self, data):
    self.board = data.copy()
        
BitBoard3x3.load = load

In [32]:
def save(self):
    return self.board, self.crossturn
 
TwoBitBoard3x3.save = save

def load(self, data):
    self.board, self.crossturn = data
        
TwoBitBoard3x3.load = load

In [33]:
def playout(self, pnum, timelimit=None):
    if timelimit is not None:   
        starttime = perf_counter()
        timelimit_pc = starttime + timelimit        
    result = {}
    for move in self.calc_legal_moves():
        result[move] = {
            self.CIRCLE: 0,
            self.CROSS: 0,
            self.DRAW: 0,
        }
    count = 0
    board = self.board.save()
    for _ in range(pnum):
        if timelimit is not None and perf_counter() > timelimit_pc:
            break
        turn = self.turn
        move_count = self.move_count
        status = self.status
        firstmove = None
        while status == self.PLAYING:
            move = random.choice(self.calc_legal_moves())
            if firstmove is None:
                firstmove = move
            self.board.setmark_by_move(move, turn)
            last_turn = turn
            turn = self.CROSS if turn == self.CIRCLE else self.CIRCLE
            move_count += 1
            status = self.board.judge(last_turn, move, move_count)
        self.board.load(board)
        result[firstmove][status] += 1
        count += 1
    return {
        "result": result,
        "count": count,
    }
    
Marubatsu.playout = playout

In [34]:
for boardclass in [ListBoard, List1dBoard, ArrayBoard, NpBoard, NpIntBoard, NpBoolBoard, BitBoard, BitBoard3x3, TwoBitBoard3x3]:
    for count_linemark in [False, True]:
        if boardclass in [BitBoard3x3, TwoBitBoard3x3] and count_linemark == True:
            continue
        print(f"boardclass = {boardclass.__name__} count_linemark = {count_linemark}")
        mb = Marubatsu(boardclass=boardclass, count_linemark=count_linemark)
        random.seed(0)
        retval = mb.playout(10000)
        move = mb.board.xy_to_move(0, 0)
        data = retval["result"][move]
        print(f"(0, 0) o {data[mb.CIRCLE]} x {data[mb.CROSS]} draw {data[mb.DRAW]}")
        retval = mb.playout(pnum=100000000, timelimit=1)
        print(f"playout count = {retval['count']}")

boardclass = ListBoard count_linemark = False
(0, 0) o 710 x 298 draw 156
playout count = 47205
boardclass = ListBoard count_linemark = True
(0, 0) o 710 x 298 draw 156
playout count = 43096
boardclass = List1dBoard count_linemark = False
(0, 0) o 710 x 298 draw 156
playout count = 75128
boardclass = List1dBoard count_linemark = True
(0, 0) o 710 x 298 draw 156
playout count = 53790
boardclass = ArrayBoard count_linemark = False
(0, 0) o 710 x 298 draw 156
playout count = 59657
boardclass = ArrayBoard count_linemark = True
(0, 0) o 710 x 298 draw 156
playout count = 48865
boardclass = NpBoard count_linemark = False
(0, 0) o 710 x 298 draw 156
playout count = 17016
boardclass = NpBoard count_linemark = True
(0, 0) o 710 x 298 draw 156
playout count = 21976
boardclass = NpIntBoard count_linemark = False
(0, 0) o 710 x 298 draw 156
playout count = 22197
boardclass = NpIntBoard count_linemark = True
(0, 0) o 710 x 298 draw 156
playout count = 30375
boardclass = NpBoolBoard count_linemark =