In [1]:
from marubatsu import NpBoolBoard, Marubatsu

mb = Marubatsu(boardclass=NpBoolBoard)
mb.cmove(0, 0)
mb.cmove(1, 0)
mb.cmove(0, 1)
mb.cmove(2, 0)
mb.cmove(1, 2)
mb.cmove(1, 1)
mb.cmove(0, 2)
print(mb)

winner o
oxx
ox.
Oo.



In [2]:
import numpy as np

na2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(na2d)
print()
print(np.rot90(na2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [3]:
print(na2d)
print()
print(np.rot90(na2d, axes=(1, 0)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [4]:
na3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                 [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(na3d)
print()
print(np.rot90(na3d))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

[[[ 7  8  9]
  [16 17 18]]

 [[ 4  5  6]
  [13 14 15]]

 [[ 1  2  3]
  [10 11 12]]]


In [5]:
print(na3d)
print()
print(np.rot90(na3d, axes=(1, 2)))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

[[[ 3  6  9]
  [ 2  5  8]
  [ 1  4  7]]

 [[12 15 18]
  [11 14 17]
  [10 13 16]]]


In [6]:
from marubatsu import NpBoolBoard

def calc_same_hashables(self, move=None):
    if move is None:
        hashables = set([self.board_to_hashable()])
    else:
        hashables = { self.board_to_hashable(): move }
    boardorig = self.board
    if move is not None:
        x, y = self.move_to_xy(move)
    for i in range(7):
        if i != 3:
            self.board = np.rot90(self.board, axes=(1, 2))
        else:
            self.board = np.flip(self.board, axis=1)
        print(mb)
        hashable = self.board_to_hashable()
        if move is None:
            hashables.add(hashable)
        else:
            if i == 3:
                y = self.BOARD_SIZE - y - 1
            else:
                x, y = self.BOARD_SIZE - y - 1, x
            hashables[hashable] = self.xy_to_move(x, y)
    self.board = boardorig
    return hashables

NpBoolBoard.calc_same_hashables = calc_same_hashables

In [7]:
print(mb)
mb.board.calc_same_hashables()

winner o
oxx
ox.
Oo.

winner o
ooo
oxx
..x

winner o
.oo
.xo
Xxo

winner o
x..
xxo
Ooo

winner o
..x
oxx
Ooo

winner o
oo.
ox.
Oxx

winner o
ooo
xxo
X..

winner o
xxo
.xo
.oo



{b'\x00\x00\x00\x00\x00\x01\x01\x01\x01\x01\x00\x00\x01\x01\x00\x00\x00\x00',
 b'\x00\x00\x00\x01\x00\x00\x01\x01\x01\x00\x00\x01\x00\x01\x01\x00\x00\x00',
 b'\x00\x00\x01\x00\x00\x01\x00\x01\x01\x01\x01\x00\x00\x01\x00\x00\x00\x00',
 b'\x00\x01\x01\x00\x00\x01\x00\x00\x01\x00\x00\x00\x00\x01\x00\x01\x01\x00',
 b'\x01\x00\x00\x01\x00\x00\x01\x01\x00\x00\x01\x01\x00\x01\x00\x00\x00\x00',
 b'\x01\x01\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x01',
 b'\x01\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x01\x00\x01\x00\x00',
 b'\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x01'}

In [8]:
def calc_same_hashables(self, move=None):
    if move is None:
        hashables = set([self.board_to_hashable()])
    else:
        hashables = { self.board_to_hashable(): move }
    boardorig = self.board
    if move is not None:
        x, y = self.move_to_xy(move)
    for i in range(7):
        if i != 3:
            self.board = np.rot90(self.board, axes=(1, 2))
        else:
            self.board = np.flip(self.board, axis=1)
        hashable = self.board_to_hashable()
        if move is None:
            hashables.add(hashable)
        else:
            if i == 3:
                y = self.BOARD_SIZE - y - 1
            else:
                x, y = self.BOARD_SIZE - y - 1, x
            hashables[hashable] = self.xy_to_move(x, y)
    self.board = boardorig
    return hashables

NpBoolBoard.calc_same_hashables = calc_same_hashables

In [9]:
from util import benchmark

for count_linemark in [False, True]:
    print(f"count_linemark {count_linemark}")
    benchmark(mbparams={"boardclass": NpBoolBoard, "count_linemark": count_linemark})
    print()

count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:06<00:00, 7407.77it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [01:05<00:00, 760.68it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 43.2 ms ±   3.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:08<00:00, 6156.21it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:28<00:00, 1765.56it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 43.2 ms ±   3.0 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



In [10]:
print(mb)
narow = np.count_nonzero(mb.board.board, axis=1)
print(narow)

winner o
oxx
ox.
Oo.

[[1 1 2]
 [2 1 0]]


In [11]:
print(mb)
narow = np.count_nonzero(mb.board.board, axis=1)
print(narow)

winner o
oxx
ox.
Oo.

[[1 1 2]
 [2 1 0]]


In [12]:
print(mb)
for i in range(mb.BOARD_SIZE):
    print(narow[:, i])

winner o
oxx
ox.
Oo.

[1 2]
[1 1]
[2 0]


In [13]:
from collections import defaultdict
from pprint import pprint

markpats = defaultdict(int)
for i in range(mb.BOARD_SIZE):
    markpats[tuple(narow[:, i])] += 1
pprint(markpats)

defaultdict(<class 'int'>,
            {(np.int64(1), np.int64(1)): 1,
             (np.int64(1), np.int64(2)): 1,
             (np.int64(2), np.int64(0)): 1})


In [14]:
%%timeit

markpats = defaultdict(int)
for i in range(mb.BOARD_SIZE):
    markpats[tuple(narow[:, i])] += 1

3.58 μs ± 94.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
%%timeit

markpats = defaultdict(int)
for i in range(mb.BOARD_SIZE):
    markpats[tuple(narow[:, i].tolist())] += 1

1.79 μs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
for data in narow:
    print(data)

[1 1 2]
[2 1 0]


In [17]:
print(narow)
print()
print(narow.T)

[[1 1 2]
 [2 1 0]]

[[1 2]
 [1 1]
 [2 0]]


In [18]:
print(np.zeros((2, 3, 4, 5, 6)).T.shape)

(6, 5, 4, 3, 2)


In [19]:
markpats = defaultdict(int)
for markpat in narow.T:
    markpats[tuple(markpat)] += 1
pprint(markpats)

defaultdict(<class 'int'>,
            {(np.int64(1), np.int64(1)): 1,
             (np.int64(1), np.int64(2)): 1,
             (np.int64(2), np.int64(0)): 1})


In [20]:
markpats = defaultdict(int)
for markpat in narow.T:
    markpats[tuple(markpat.tolist())] += 1
pprint(markpats)

defaultdict(<class 'int'>, {(1, 2): 1, (1, 1): 1, (2, 0): 1})


In [21]:
%%timeit

markpats = defaultdict(int)
for markpat in narow.T:
    markpats[tuple(markpat)] += 1

3.91 μs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
%%timeit

markpats = defaultdict(int)
for markpat in narow.T:
    markpats[tuple(markpat.tolist())] += 1   

2.25 μs ± 210 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
%%timeit

markpats = defaultdict(int)
for markpat in narow.T.tolist():
    markpats[tuple(markpat)] += 1

1.18 μs ± 16.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [24]:
mb2 = Marubatsu(boardclass=NpBoolBoard)
mb2.cmove(0, 0)
mb2.cmove(1, 0)
mb2.cmove(0, 1)
mb2.cmove(2, 0)
mb2.cmove(1, 2)
mb2.cmove(1, 1)
print(mb2)

narow2 = np.count_nonzero(mb2.board.board, axis=1).T
markpats = defaultdict(int)
if mb2.turn == mb.CIRCLE:
    narow2 = np.flip(narow2, axis=1)
for markpat in narow2.tolist():
    markpats[tuple(markpat)] += 1
print(markpats)

Turn o
oxx
oX.
.o.

defaultdict(<class 'int'>, {(2, 1): 1, (1, 1): 1, (0, 1): 1})


In [25]:
l2d = narow2.tolist()
print(l2d)
print([tuple(data) for data in l2d])

[[2, 1], [1, 1], [0, 1]]
[(2, 1), (1, 1), (0, 1)]


In [26]:
from collections import Counter

narow2 = np.count_nonzero(mb2.board.board, axis=1).T
if mb2.turn == mb.CIRCLE:
    narow2 = np.flip(narow2, axis=1)
markpats = Counter([tuple(data) for data in narow2.tolist()])
print(markpats)

Counter({(2, 1): 1, (1, 1): 1, (0, 1): 1})


In [27]:
%%timeit

narow = np.count_nonzero(mb.board.board, axis=1)
markpats = defaultdict(int)
if mb.turn == mb.CIRCLE:
    narow = np.flip(narow, axis=0)
for markpat in narow.T.tolist():
    markpats[tuple(markpat)] += 1

5.92 μs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [28]:
%%timeit

narow = np.count_nonzero(mb.board.board, axis=1)
if mb.turn == mb.CIRCLE:
    narow = np.flip(narow, axis=0)
markpats = Counter([tuple(data) for data in narow.T.tolist()])

6.8 μs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
print(mb2)
nacol = np.count_nonzero(mb2.board.board, axis=2).T
if mb2.turn == mb2.CIRCLE:
    nacol = np.flip(nacol, axis=1)
markpats = Counter([tuple(data) for data in nacol.tolist()])
print(markpats)

Turn o
oxx
oX.
.o.

Counter({(0, 2): 1, (2, 1): 1, (1, 0): 1})


In [30]:
na2d1 = np.array([[1, 2], [3, 4]])
na2d2 = np.array([[5, 6], [7, 8]])
print(na2d1)
print()
print(na2d2)
print()
print(np.concatenate([na2d1, na2d2], axis=0))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
print(na2d1)
print()
print(na2d2)
print()
print(np.concatenate([na2d1, na2d2], axis=1))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [32]:
na3d1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
na3d2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print(na3d1)
print()
print(na3d2)
print()
print(np.concatenate([na3d1, na3d2], axis=2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [33]:
na5d1 = np.zeros((2, 3, 4, 5, 6))
na5d2 = np.zeros((2, 3, 7, 5, 6))
na5d3 = np.zeros((2, 3, 8, 5, 6))
print(np.concatenate([na5d1, na5d2, na5d3], axis=2).shape)

(2, 3, 19, 5, 6)


In [34]:
print(mb)
narow = np.count_nonzero(mb.board.board, axis=1).T
nacol = np.count_nonzero(mb.board.board, axis=2).T
napat = np.concatenate([narow, nacol], axis=0)
print(napat)
if mb.turn == mb.CIRCLE:
    napat = np.flip(napat, axis=1)
markpats = Counter([tuple(data) for data in napat.tolist()])
print(markpats)
    

winner o
oxx
ox.
Oo.

[[1 2]
 [1 1]
 [2 0]
 [3 0]
 [1 2]
 [0 1]]
Counter({(1, 2): 2, (1, 1): 1, (2, 0): 1, (3, 0): 1, (0, 1): 1})


In [35]:
na1d1 = np.array([1, 2, 3])
na1d2 = np.array([4, 5, 6])
print(np.vstack([na1d1, na1d2]))
    

[[1 2 3]
 [4 5 6]]


In [36]:
print(np.vstack([na2d1, na2d2]))
print()
print(np.concatenate([na2d1, na2d2], axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
print(np.vstack([na3d1, na3d2]))
print()
print(np.concatenate([na3d1, na3d2], axis=0))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [38]:
print(na1d1)
print(na1d2)
print(np.hstack([na1d1, na1d2]))

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [39]:
print(np.hstack([na2d1, na2d2]))
print()
print(np.concatenate([na2d1, na2d2], axis=1))

[[1 2 5 6]
 [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [40]:
print(np.hstack([na3d1, na3d2]))
print()
print(np.concatenate([na3d1, na3d2], axis=1))

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


In [41]:
print(np.concat([na3d1, na3d2], axis=0))

print(np.concatenate([na3d1, na3d2], axis=0))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [42]:
print(np.count_nonzero(np.diagonal(mb.board.board, axis1=1, axis2=2), axis=1))

[1 1]


In [43]:
print(na1d1)
print(na1d1.shape)
print(na1d1[np.newaxis, :])
print(na1d1[np.newaxis, :].shape)


[1 2 3]
(3,)
[[1 2 3]]
(1, 3)


In [44]:
print(mb)
narow = np.count_nonzero(mb.board.board, axis=1).T
nacol = np.count_nonzero(mb.board.board, axis=2).T
nadiag1 = np.count_nonzero(np.diagonal(mb.board.board, axis1=1, axis2=2), axis=1)[np.newaxis, :]
nadiag2 = np.count_nonzero(np.diagonal(np.flip(mb.board.board, axis=2),
                                       axis1=1, axis2=2), axis=1)[np.newaxis, :]
napat = np.concatenate([narow, nacol, nadiag1, nadiag2], axis=0)
print(napat)
if mb.turn == mb.CIRCLE:
    napat = np.flip(napat, axis=1)
markpats = Counter([tuple(data) for data in napat.tolist()])
print(markpats)

winner o
oxx
ox.
Oo.

[[1 2]
 [1 1]
 [2 0]
 [3 0]
 [1 2]
 [0 1]
 [1 1]
 [1 2]]
Counter({(1, 2): 3, (1, 1): 2, (2, 0): 1, (3, 0): 1, (0, 1): 1})


In [45]:
def count_markpats3(self, turn, last_turn):
    if self.count_linemark:
        markpats = defaultdict(int)
        for countdict in [self.rowcount, self.colcount, self.diacount]:
            for circlecount, crosscount in zip(countdict[self.CIRCLE], countdict[self.CROSS]):
                emptycount = self.BOARD_SIZE - circlecount - crosscount
                if last_turn == self.CIRCLE:
                    markpats[(circlecount, crosscount, emptycount)] += 1
                else:
                    markpats[(crosscount, circlecount, emptycount)] += 1
    else:
        narow = np.count_nonzero(self.board, axis=1).T
        nacol = np.count_nonzero(self.board, axis=2).T
        nadiag1 = np.count_nonzero(np.diagonal(self.board, axis1=1, axis2=2), axis=1)[np.newaxis, :]
        nadiag2 = np.count_nonzero(np.diagonal(np.flip(self.board, axis=2),
                                               axis1=1, axis2=2), axis=1)[np.newaxis, :]
        napat = np.concatenate([narow, nacol, nadiag1, nadiag2], axis=0)
        if turn == self.CIRCLE:
            napat = np.flip(napat, axis=1)
        markpats = Counter([tuple(data) for data in napat.tolist()])

    return markpats  

NpBoolBoard.count_markpats3 = count_markpats3

In [46]:
mb.board.count_markpats3(mb.turn, mb.last_turn)

Counter({(1, 2): 3, (1, 1): 2, (2, 0): 1, (3, 0): 1, (0, 1): 1})

In [47]:
%timeit mb.count_markpats()
%timeit mb.board.count_markpats2(mb.turn, mb.last_turn)
%timeit mb.board.count_markpats3(mb.turn, mb.last_turn)

18.4 μs ± 1.05 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
29 μs ± 1.23 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
28.6 μs ± 923 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
