In [1]:
import numpy as np

nd1d = np.array([1, 2, 3, 4, 5])
print(nd1d)

[1 2 3 4 5]


In [2]:
nd2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(nd2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
nd3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])
print(nd3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [4]:
l2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(nd2d[1][2])
print(l2d[1][2])

6
6


In [5]:
print(nd2d[1, 2])

6


In [6]:
print(nd2d[:][1])
print(l2d[:][1])
print(nd2d[:, 1])

[4 5 6]
[4, 5, 6]
[2 5 8]


In [7]:
print(nd2d[1])
print(nd2d[:][1])
print(l2d[1])
print(l2d[:][1])

[4 5 6]
[4 5 6]
[4, 5, 6]
[4, 5, 6]


In [8]:
print(nd2d[1, 2])

6


In [9]:
print(nd2d[1, :])

[4 5 6]


In [10]:
print(nd3d[(0, )])
print(nd3d[0, :])
print(nd3d[0, :, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
%timeit nd3d[(0, )]
%timeit nd3d[0, :]
%timeit nd3d[0, :, :]

119 ns ± 1.37 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
180 ns ± 4.22 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
260 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
print(nd1d[1])

2


In [13]:
print(type(nd1d[1]))
print(nd1d.dtype)

<class 'numpy.int64'>
int64


In [14]:
print(nd2d[1, :])
print(nd2d[:, 1])

[4 5 6]
[2 5 8]


In [15]:
print(nd3d[0, :, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(nd3d[:, 0, :])

[[ 1  2  3]
 [10 11 12]]


In [17]:
print(nd3d[0, 0, :])

[1 2 3]


In [18]:
print(nd2d.shape)
print(nd2d[0:2, :])
print(nd2d[0:2, :].shape)


(3, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
print(nd3d.shape)
print(nd3d[:, ::2, :])
print(nd3d[:, ::2, :].shape)

(2, 3, 3)
[[[ 1  2  3]
  [ 7  8  9]]

 [[10 11 12]
  [16 17 18]]]
(2, 2, 3)
