In [1]:
from array import array

a = array("i")
print(a)

array('i')


In [2]:
a = array("i", [1, 2, 3])
print(a)

array('i', [1, 2, 3])


In [3]:
print(a[0])
a[0] = 5
print(a[0])
print(a)

1
5
array('i', [5, 2, 3])


In [4]:
a.append(10)
print(a)

array('i', [5, 2, 3, 10])


In [5]:
a[0] = "x"

TypeError: 'str' object cannot be interpreted as an integer

In [6]:
from marubatsu import Marubatsu, List1dBoard

class ArrayBoard(List1dBoard):
    def __init__(self, board_size=3, count_linemark=False):
        self.BOARD_SIZE = board_size
        self.count_linemark = count_linemark
        self.board = array("w", [Marubatsu.EMPTY] * (self.BOARD_SIZE ** 2))
        if self.count_linemark:
            self.rowcount = {
                Marubatsu.CIRCLE: [0] * self.BOARD_SIZE,
                Marubatsu.CROSS: [0] * self.BOARD_SIZE,
            }
            self.colcount = {
                Marubatsu.CIRCLE: [0] * self.BOARD_SIZE,
                Marubatsu.CROSS: [0] * self.BOARD_SIZE,
            }
            self.diacount = {
                Marubatsu.CIRCLE: [0] * 2,
                Marubatsu.CROSS: [0] * 2,
            }

In [7]:
from util import benchmark

boardclass = ArrayBoard
for count_linemark in [False, True]:
    print(f"boardclass: {boardclass.__name__}, count_linemark {count_linemark}")
    benchmark(mbparams={"boardclass": boardclass, "count_linemark": count_linemark})
    print()

boardclass: ArrayBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 14702.96it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:48<00:00, 1023.88it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 18.8 ms ±   1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: ArrayBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 14645.31it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:26<00:00, 1903.46it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 19.8 ms ±   1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



In [8]:
l = [i for i in range(1000000)]
a = array("i", l) 
print("参照")
print("list")
%timeit l[0]
print("array")
%timeit a[0]
print("代入")
print("list")
%timeit l[0] = 1
print("array")
%timeit a[0] = 1

参照
list
22.6 ns ± 2.29 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
array
35.2 ns ± 1.47 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
代入
list
22.9 ns ± 1.4 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
array
54.7 ns ± 0.967 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [9]:
from copy import copy, deepcopy

print("copy")
print("list")
%timeit copy(l)
print("array")
%timeit copy(a)
print("deepcopy")
print("list")
%timeit deepcopy(l)
print("array")
%timeit deepcopy(a)

copy
list
9.47 ms ± 164 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
array
1.06 ms ± 22.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
deepcopy
list
277 ms ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
array
1.09 ms ± 15.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
from sys import getsizeof

print(getsizeof(1))

28


In [11]:
print("list")
size = getsizeof(l)
for data in l:
    size += getsizeof(data)
print(size)
print("array")
print(getsizeof(a))

list
36448728
array
4000080


In [12]:
import numpy as np

In [13]:
print(np.__version__)

2.3.2


In [14]:
lista = [1, 2, 3]
listb = [[1, 2], [3, 4], [5, 6]]
arraya = np.array(lista)
arrayb = np.array(listb)
print(lista)
print(arraya)
print(listb)
print(arrayb)

[1, 2, 3]
[1 2 3]
[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(arraya.dtype)

int64


In [16]:
print(arraya.ndim)
print(arraya.shape)
print(arrayb.ndim)
print(arrayb.shape)

1
(3,)
2
(3, 2)


In [17]:
lista[2] = 5
arraya[2] = 5
print(lista[2])
print(lista)
print(arraya[2])
print(arraya)
listb[0][1] = 5
arrayb[0][1] = 5
print(listb[0][1])
print(listb)
print(arrayb[0][1])
print(arrayb)

5
[1, 2, 5]
5
[1 2 5]
5
[[1, 5], [3, 4], [5, 6]]
5
[[1 5]
 [3 4]
 [5 6]]


In [18]:
from marubatsu import ListBoard

class NpBoard(ListBoard):
    def __init__(self, board_size=3, count_linemark=False):
        self.BOARD_SIZE = board_size
        self.count_linemark = count_linemark
        self.board = np.array([[Marubatsu.EMPTY] * self.BOARD_SIZE for y in range(self.BOARD_SIZE)])
        if self.count_linemark:
            self.rowcount = {
                Marubatsu.CIRCLE: [0] * self.BOARD_SIZE,
                Marubatsu.CROSS: [0] * self.BOARD_SIZE,
            }
            self.colcount = {
                Marubatsu.CIRCLE: [0] * self.BOARD_SIZE,
                Marubatsu.CROSS: [0] * self.BOARD_SIZE,
            }
            self.diacount = {
                Marubatsu.CIRCLE: [0] * 2,
                Marubatsu.CROSS: [0] * 2,
            }

In [19]:
npb = NpBoard()
print(npb.board)
print(npb.board.dtype)
print(npb.board.ndim)
print(npb.board.shape)

[['.' '.' '.']
 ['.' '.' '.']
 ['.' '.' '.']]
<U1
2
(3, 3)


In [20]:
boardclass = NpBoard
for count_linemark in [False, True]:
    print(f"boardclass: {boardclass.__name__}, count_linemark {count_linemark}")
    benchmark(mbparams={"boardclass": boardclass, "count_linemark": count_linemark})
    print()

boardclass: NpBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:08<00:00, 5924.49it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [01:18<00:00, 633.71it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 42.9 ms ±   1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: NpBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:07<00:00, 6832.91it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:33<00:00, 1475.99it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 43.1 ms ±   1.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



In [21]:
n = np.array(l)
print("参照")
print("list")
%timeit l[0]
print("array")
%timeit a[0]
print("numpy")
%timeit n[0]
print("代入")
print("list")
%timeit l[0] = 1
print("array")
%timeit a[0] = 1
print("numpy")
%timeit n[0] = 1

参照
list
23.1 ns ± 1.49 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
array
36.2 ns ± 1.5 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
numpy
72.3 ns ± 2.29 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
代入
list
22.5 ns ± 0.176 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
array
57.9 ns ± 2.81 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
numpy
69.5 ns ± 1.49 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
