In [1]:
from marubatsu import NpBoolBoard, Marubatsu

mb = Marubatsu(boardclass=NpBoolBoard)
mb.cmove(0, 0)
mb.cmove(1, 0)
mb.cmove(0, 1)
mb.cmove(2, 0)
mb.cmove(1, 2)
mb.cmove(1, 1)
mb.cmove(0, 2)
print(mb)

winner o
oxx
ox.
Oo.



In [2]:
print(mb.board.board[:, 0, :])

[[ True  True  True]
 [False False False]]


In [3]:
print(mb.board.board[:, :, 0])

[[ True False False]
 [False  True  True]]


In [4]:
import numpy as np

print(np.diag(mb.board.board[0, :, :]))
print(np.diag(mb.board.board[1, :, :]))

[ True False False]
[False  True False]


In [5]:
na3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                 [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(na3d)         
print()   
print("np.diagonal")
print(np.diagonal(na3d, axis1=1, axis2=2))


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

np.diagonal
[[ 1  5  9]
 [10 14 18]]


In [6]:
print(np.diagonal(mb.board.board, axis1=1, axis2=2))

[[ True False False]
 [False  True False]]


In [7]:
print(np.diagonal(mb.board.board, axis1=2, axis2=1))

[[ True False False]
 [False  True False]]


In [8]:
na = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(na)
print("offset = 0, axis1 = 0, axis2 = 1")
print(np.diagonal(na, offset=0, axis1=0, axis2=1))
print("offset = 1, axis1 = 0, axis2 = 1")
print(np.diagonal(na, offset=1, axis1=0, axis2=1))
print("offset = -1, axis1 = 0, axis2 = 1")
print(np.diagonal(na, offset=-1, axis1=0, axis2=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
offset = 0, axis1 = 0, axis2 = 1
[1 5 9]
offset = 1, axis1 = 0, axis2 = 1
[2 6]
offset = -1, axis1 = 0, axis2 = 1
[4 8]


In [9]:
na = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(na)
print("offset = 0, axis1 = 1, axis2 = 0")
print(np.diagonal(na, offset=0, axis1=1, axis2=0))
print("offset = 1, axis1 = 1, axis2 = 0")
print(np.diagonal(na, offset=1, axis1=1, axis2=0))
print("offset = -1, axis1 = 1, axis2 = 0")
print(np.diagonal(na, offset=-1, axis1=1, axis2=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
offset = 0, axis1 = 1, axis2 = 0
[1 5 9]
offset = 1, axis1 = 1, axis2 = 0
[4 8]
offset = -1, axis1 = 1, axis2 = 0
[2 6]


In [10]:
%%timeit

np.diag(mb.board.board[0])
np.diag(mb.board.board[1])

2.96 μs ± 78.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
%timeit np.diagonal(mb.board.board, axis1=1, axis2=2)

940 ns ± 36.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
print(np.fliplr(na))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [13]:
print("元のデータ")
print(mb.board.board)
print()
print("np.fliplr の結果")
print(np.fliplr(mb.board.board))

元のデータ
[[[ True  True  True]
  [False False  True]
  [False False False]]

 [[False False False]
  [ True  True False]
  [ True False False]]]

np.fliplr の結果
[[[False False False]
  [False False  True]
  [ True  True  True]]

 [[ True False False]
  [ True  True False]
  [False False False]]]


In [14]:
print("元のデータ")
print(mb.board.board)
print()
print("np.flip の結果")
print(np.flip(mb.board.board, axis=2))


元のデータ
[[[ True  True  True]
  [False False  True]
  [False False False]]

 [[False False False]
  [ True  True False]
  [ True False False]]]

np.flip の結果
[[[ True  True  True]
  [ True False False]
  [False False False]]

 [[False False False]
  [False  True  True]
  [False False  True]]]


In [15]:
print(np.diagonal(np.flip(mb.board.board, axis=2), axis1=2, axis2=1))

[[ True False False]
 [False  True  True]]


In [16]:
from collections import defaultdict

def count_markpats(self, turn, last_turn):
    markpats = defaultdict(int)
    
    if self.count_linemark:
        for countdict in [self.rowcount, self.colcount, self.diacount]:
            for circlecount, crosscount in zip(countdict[self.CIRCLE], countdict[self.CROSS]):
                emptycount = self.BOARD_SIZE - circlecount - crosscount
                if last_turn == self.CIRCLE:
                    markpats[(circlecount, crosscount, emptycount)] += 1
                else:
                    markpats[(crosscount, circlecount, emptycount)] += 1
    else:
        # 横方向と縦方向の判定
        for i in range(self.BOARD_SIZE):
            count = self.count_marks(self.board[:, i, :], turn, last_turn)
            markpats[count] += 1
            count = self.count_marks(self.board[:, :, i], turn, last_turn)
            markpats[count] += 1
        # 左上から右下方向の判定
        count = self.count_marks(np.diagonal(self.board, axis1=1, axis2=2), turn, last_turn)
        markpats[count] += 1
        # 右上から左下方向の判定
        count = self.count_marks(np.diagonal(np.flip(self.board, axis=2), axis1=1, axis2=2),
                                 turn, last_turn)
        markpats[count] += 1

    return markpats

NpBoolBoard.count_markpats = count_markpats

In [17]:
def count_marks(self, linedata, turn, last_turn):
    turn_count = np.count_nonzero(linedata[turn])
    lastturn_count = np.count_nonzero(linedata[last_turn])
    emptycount = self.BOARD_SIZE - turn_count - lastturn_count
    return lastturn_count, turn_count, emptycount

NpBoolBoard.count_marks = count_marks

In [18]:
from pprint import pprint

print(mb)
pprint(mb.count_markpats())

winner o
oxx
ox.
Oo.

defaultdict(<class 'int'>,
            {(np.int64(0), np.int64(1), np.int64(2)): 1,
             (np.int64(1), np.int64(1), np.int64(1)): 2,
             (np.int64(1), np.int64(2), np.int64(0)): 3,
             (np.int64(2), np.int64(0), np.int64(1)): 1,
             (np.int64(3), np.int64(0), np.int64(0)): 1})


In [19]:
from ai import ai_match, ai2, ai14s
import random

random.seed(0)
ai_match(ai=[ai2, ai2], match_num=50000, mbparams={"boardclass": NpBoolBoard})
ai_match(ai=[ai14s, ai2], match_num=50000, mbparams={"boardclass": NpBoolBoard})
random.seed(0)
ai_match(ai=[ai2, ai2], match_num=50000, mbparams={"boardclass": NpBoolBoard, "count_linemark": True})
ai_match(ai=[ai14s, ai2], match_num=50000, mbparams={"boardclass": NpBoolBoard, "count_linemark": True})

ai2 VS ai2


100%|██████████| 50000/50000 [00:09<00:00, 5555.23it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [01:04<00:00, 779.70it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai2 VS ai2


100%|██████████| 50000/50000 [00:07<00:00, 6596.47it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:27<00:00, 1807.04it/s]

count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%



[('count',
  [{'win': 49446, 'lose': 0, 'draw': 554},
   {'win': 44043, 'lose': 0, 'draw': 5957},
   {'win': 93489, 'lose': 0, 'draw': 6511}],
  '7d'),
 ('ratio',
  [{'win': 0.98892, 'lose': 0.0, 'draw': 0.01108},
   {'win': 0.88086, 'lose': 0.0, 'draw': 0.11914},
   {'win': 0.93489, 'lose': 0.0, 'draw': 0.06511}],
  '7.1%')]