In [1]:
import numpy as np

i = np.int64(10)
print(i)
print(i.dtype)

10
int64


In [2]:
a = np.full((3, ), 0, dtype=np.int8)
print(a)
print(a.dtype)
a = np.full((3, ), 0, dtype="int8")
print(a)
print(a.dtype)
a = np.full((3, ), 0, dtype="i1")
print(a)
print(a.dtype)

[0 0 0]
int8
[0 0 0]
int8
[0 0 0]
int8


In [3]:
i = np.int_(10)
print(i)
print(i.dtype)

10
int64


In [4]:
a = np.full((3, ), 0, dtype="int_")
print(a)
print(a.dtype)
a = np.full((3, ), 0, dtype="int")
print(a)
print(a.dtype)
a = np.full((3, ), 0, dtype="bool_")
print(a)
print(a.dtype)
a = np.full((3, ), 0, dtype="bool")
print(a)
print(a.dtype)

[0 0 0]
int64
[0 0 0]
int64
[False False False]
bool
[False False False]
bool


In [5]:
i = np.full((3, ), 0, dtype=np.int64)
print(i)
print(i.dtype)
i = np.full((3, ), 0, dtype="int64")
print(i)
print(i.dtype)
i = np.full((3, ), 0, dtype="i8")
print(i)
print(i.dtype)

[0 0 0]
int64
[0 0 0]
int64
[0 0 0]
int64


In [6]:
dt = np.dtype("i4, (2,3)f8, f4")
dt

dtype([('f0', '<i4'), ('f1', '<f8', (2, 3)), ('f2', '<f4')])

In [7]:
i = np.zeros((3, ), dtype=np.int8)
i[0] = 1000

OverflowError: Python integer 1000 out of bounds for int8

In [8]:
print(np.iinfo(np.uint16))
print(np.iinfo(np.int16))

Machine parameters for uint16
---------------------------------------------------------------
min = 0
max = 65535
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------



In [9]:
f = np.full((3, ), 0, dtype=np.float64)
print(f)
print(f.dtype)
f = np.full((3, ), 0, dtype="float64")
print(f)
print(f.dtype)
f = np.full((3, ), 0, dtype="f8")
print(f)
print(f.dtype)

[0. 0. 0.]
float64
[0. 0. 0.]
float64
[0. 0. 0.]
float64


In [10]:
print(np.float16(1000000))

inf


C:\Users\ys\AppData\Local\Temp\ipykernel_261700\2302096247.py:1: RuntimeWarning: overflow encountered in cast
  print(np.float16(1000000))


In [11]:
print(np.finfo(np.float64))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



In [12]:
b = np.full((3, ), False, dtype=np.bool_)
print(b)
print(b.dtype)
b = np.full((3, ), False, dtype=np.bool)
print(b)
print(b.dtype)
b = np.full((3, ), False, dtype="bool_")
print(b)
print(b.dtype)
b = np.full((3, ), False, dtype="bool")
print(b)
print(b.dtype)
b = np.full((3, ), False, dtype="?")
print(i)
print(i.dtype)

[False False False]
bool
[False False False]
bool
[False False False]
bool
[False False False]
bool
[0 0 0]
int8


In [13]:
print(np.full((3, ), False, dtype=np.bool_).tobytes())
print(np.full((3, ), False, dtype="?").tobytes())

b'\x00\x00\x00'
b'\x00\x00\x00'


In [14]:
s = np.str_("abc")
print(s)
print(len(s))

abc
3


In [15]:
print(s.dtype)

<U3


In [16]:
s1 = np.array(["a", "bc", "def"])
print(s1)
print(s.dtype)
s2 = np.full((3, ), "", dtype="<U5")
print(s2)
print(s2.dtype)

['a' 'bc' 'def']
<U3
['' '' '']
<U5


In [17]:
s2[0] = "abcdefg"
print(s2)

['abcde' '' '']


In [18]:
ndarray = np.array([1, 2, 3], dtype=np.float64)
print(ndarray)
print(ndarray.dtype)

[1. 2. 3.]
float64


In [19]:
ndarray = np.array([1.0, 1.5, 2.0], dtype=np.int64)
print(ndarray)
print(ndarray.dtype)

[1 1 2]
int64


In [20]:
ndarray = np.array([123456789], dtype=np.float32)
print(ndarray)
print(ndarray.dtype)

[1.2345679e+08]
float32


In [21]:
print(np.full((3, ), "a", dtype=np.int64))

ValueError: invalid literal for int() with base 10: np.str_('a')

In [22]:
datalist = [
    [1, 2, 3],           # int（整数）のみを要素とする list
    [1.0, 1.5, 2.0],     # float（浮動小数点数）のみを要素とする list
    ["a", "b", "c"],     # 1 文字の str（文字列）のみを要素とする list
    ["a", "bc", "def"],  # 最長 3 文字の str（文字列）を要素とする list
    ["", "", ""],        # 0 文字の str（文字列）のみを要素とする list
    [True, False],       # bool（論理型）を要素とする list
    [1, 2.0],            # int と float が混じった list
    [1, "a"],            # int と str が混じった list
]

for data in datalist:
    ndarray = np.array(data)
    print(ndarray)
    print(ndarray.dtype)

[1 2 3]
int64
[1.  1.5 2. ]
float64
['a' 'b' 'c']
<U1
['a' 'bc' 'def']
<U3
['' '' '']
<U1
[ True False]
bool
[1. 2.]
float64
['1' 'a']
<U21


In [23]:
ndarray = np.zeros((5, ))
print(ndarray)
print(ndarray.dtype)
ndarray = np.zeros((5, ), dtype=np.int64)
print(ndarray)
print(ndarray.dtype)

[0. 0. 0. 0. 0.]
float64
[0 0 0 0 0]
int64


In [24]:
print(np.zeros((3, ), dtype=np.bool_))
print(np.ones((3, ), dtype=np.bool_))

[False False False]
[ True  True  True]


In [25]:
datalist = [
    1,      # int
    1.5,    # float
    "a",    # 1 文字の str
    "abc",  # 3 文字の str
    True,   # bool
]

for data in datalist:
    ndarray = np.full((5, ), data)
    print(ndarray)
    print(ndarray.dtype)

[1 1 1 1 1]
int64
[1.5 1.5 1.5 1.5 1.5]
float64
['a' 'a' 'a' 'a' 'a']
<U1
['abc' 'abc' 'abc' 'abc' 'abc']
<U3
[ True  True  True  True  True]
bool


In [26]:
ndarray = np.array([1, 2, 3])
print(ndarray)
print(ndarray.dtype)
ndarray2 = ndarray.astype(np.float64)
print(ndarray2)
print(ndarray2.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64


In [27]:
# np.int64 と np.float64 の比較
b1 = np.int64(10) == np.float64(10)
print(b1)
print(b1.dtype)
# np.int64 と Python の int の比較
b2 = np.int64(10) == 10
print(b2)
print(b2.dtype)
# np.int64 と np.float64 の ndarray の比較
a1 = np.array([1, 2, 3])
a2 = np.array([2., 2., 2.])
b3 = a1 <= a2
print(b3)
print(b3.dtype)
# np.int64 と Python の int の比較
b4 = a1 > 1
print(b4)
print(b4.dtype)

True
bool
True
bool
[ True  True False]
bool
[False  True  True]
bool


In [28]:
i1 = np.int8(10)
i2 = np.int16(20)
i3 = i1 + i2
print(i3)
print(i3.dtype)

30
int16


In [29]:
a1 = np.zeros((10000, ), dtype=np.int16)
print(a1.nbytes)
a2 = np.zeros((10000, ), dtype=np.int64)
print(a2.nbytes)

20000
80000


In [30]:
np.zeros((1000000000000,))

MemoryError: Unable to allocate 7.28 TiB for an array with shape (1000000000000,) and data type float64