In [1]:
from marubatsu import ListBoard, List1dBoard, ArrayBoard, NpBoard
from util import benchmark

for boardclass in [ListBoard, List1dBoard, ArrayBoard, NpBoard]:
    for count_linemark in [False, True]:
        print(f"boardclass: {boardclass.__name__}, count_linemark {count_linemark}")
        benchmark(mbparams={"boardclass": boardclass, "count_linemark": count_linemark})
        print()

boardclass: ListBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 13363.96it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:34<00:00, 1445.99it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 18.5 ms ±   2.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: ListBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 13041.36it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:21<00:00, 2326.89it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 19.4 ms ±   3.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: List1dBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 16417.96it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:35<00:00, 1390.08it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 17.7 ms ±   2.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: List1dBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 14520.57it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:21<00:00, 2285.08it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 19.3 ms ±   2.0 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: ArrayBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 14661.93it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:36<00:00, 1355.45it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 19.0 ms ±   1.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: ArrayBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:03<00:00, 13761.60it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:23<00:00, 2167.56it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 19.9 ms ±   1.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: NpBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:08<00:00, 5972.04it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [01:12<00:00, 692.95it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 50.4 ms ±   2.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: NpBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:06<00:00, 7478.88it/s]


count     win    lose    draw
o       29454   14352    6194
x       14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
o       58.9%   28.7%   12.4%
x       28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:26<00:00, 1894.42it/s]


count     win    lose    draw
o       49446       0     554
x       44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
o       98.9%    0.0%    1.1%
x       88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 45.0 ms ±   3.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



In [2]:
from util import gui_play

gui_play()

In [3]:
from mbtest import test_judge

for boardclass in [ListBoard, List1dBoard, ArrayBoard, NpBoard]:
    for count_linemark in [False, True]:
        print(f"boardclass: {boardclass.__name__}, count_linemark {count_linemark}")
        test_judge(mbparams={"boardclass": boardclass, "count_linemark": count_linemark})
        print()

boardclass: ListBoard, count_linemark False
Start
test winner = playing
oooooooooo
test winner = o
ooooooooo
test winner = x
oooooooo
test winner = draw
o
Finished

boardclass: ListBoard, count_linemark True
Start
test winner = playing
oooooooooo
test winner = o
ooooooooo
test winner = x
oooooooo
test winner = draw
o
Finished

boardclass: List1dBoard, count_linemark False
Start
test winner = playing
oooooooooo
test winner = o
ooooooooo
test winner = x
oooooooo
test winner = draw
o
Finished

boardclass: List1dBoard, count_linemark True
Start
test winner = playing
oooooooooo
test winner = o
ooooooooo
test winner = x
oooooooo
test winner = draw
o
Finished

boardclass: ArrayBoard, count_linemark False
Start
test winner = playing
oooooooooo
test winner = o
ooooooooo
test winner = x
oooooooo
test winner = draw
o
Finished

boardclass: ArrayBoard, count_linemark True
Start
test winner = playing
oooooooooo
test winner = o
ooooooooo
test winner = x
oooooooo
test winner = draw
o
Finished

boardcl

In [4]:
class NpIntBoard(NpBoard):
    EMPTY = 0
    CIRCLE = 1
    CROSS = 2

In [7]:
from marubatsu import Marubatsu

mb = Marubatsu(boardclass=NpIntBoard)
print(mb.board.board)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
print(mb)

TypeError: can only concatenate str (not "int") to str

In [8]:
Marubatsu.EMPTY_STR = "."
Marubatsu.CIRCLE_STR = "o"
Marubatsu.CROSS_STR = "x"

In [9]:
class NpIntBoard(NpBoard):
    EMPTY = 0
    CIRCLE = 1
    CROSS = 2
    MARK_TABLE = {
        EMPTY: Marubatsu.EMPTY_STR,
        CIRCLE: Marubatsu.CIRCLE_STR,
        CROSS: Marubatsu.CROSS_STR,
        Marubatsu.DRAW: Marubatsu.DRAW,        
    }

In [10]:
def __str__(self):
    if self.status == self.PLAYING:
        text = "Turn " + self.board.MARK_TABLE[self.turn] + "\n"
    # 決着がついていれば勝者を表示する
    else:
        text = "winner " + self.board.MARK_TABLE[self.status] + "\n"
    for y in range(self.BOARD_SIZE):
        for x in range(self.BOARD_SIZE):
            lastx, lasty = self.board.move_to_xy(self.last_move)
            mark = self.board.MARK_TABLE[self.board.getmark(x, y)]
            if x == lastx and y == lasty:
                text += mark.upper()
            else:
                text += mark
        text += "\n"
    return text

Marubatsu.__str__ = __str__

In [11]:
mb = Marubatsu(boardclass=NpIntBoard)
# 〇 の手番の局面
print(mb)
# × の手番の局面
mb.cmove(0, 0)
print(mb)
# 〇 の勝利の局面
mb.cmove(1, 0)
mb.cmove(0, 1)
mb.cmove(1, 1)
mb.cmove(0, 2)
print(mb)
# × の勝利の局面
mb = Marubatsu(boardclass=NpIntBoard)
mb.cmove(0, 0)
mb.cmove(1, 0)
mb.cmove(0, 1)
mb.cmove(1, 1)
mb.cmove(2, 0)
mb.cmove(1, 2)
print(mb)
# 引き分けの局面
mb = Marubatsu(boardclass=NpIntBoard)
mb.cmove(0, 0)
mb.cmove(1, 0)
mb.cmove(0, 1)
mb.cmove(1, 1)
mb.cmove(1, 2)
mb.cmove(0, 2)
mb.cmove(2, 0)
mb.cmove(2, 1)
mb.cmove(2, 2)
print(mb)


Turn o
...
...
...

Turn x
O..
...
...

winner o
ox.
ox.
O..

winner x
oxo
ox.
.X.

winner draw
oxo
oxx
xoO



In [12]:
print(mb.board_to_str())

TypeError: sequence item 0: expected str instance, int found

In [13]:
def board_to_str(self):
    numlist = self.board.flatten().tolist()
    strlist = [self.MARK_TABLE[mark] for mark in numlist]
    return "".join(strlist)

NpIntBoard.board_to_str = board_to_str

In [14]:
print(mb.board_to_str())

ooxxxooxo


In [15]:
boardclass = NpIntBoard
for count_linemark in [False, True]:
    print(f"boardclass: {boardclass.__name__}, count_linemark {count_linemark}")
    benchmark(mbparams={"boardclass": boardclass, "count_linemark": count_linemark})
    print()

boardclass: NpIntBoard, count_linemark False
ai2 VS ai2


100%|██████████| 50000/50000 [00:06<00:00, 7185.05it/s]


count     win    lose    draw
    1   29454   14352    6194
    2   14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
    1   58.9%   28.7%   12.4%
    2   28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [01:09<00:00, 723.75it/s]


count     win    lose    draw
    1   49446       0     554
    2   44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
    1   98.9%    0.0%    1.1%
    2   88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 51.7 ms ±   2.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

boardclass: NpIntBoard, count_linemark True
ai2 VS ai2


100%|██████████| 50000/50000 [00:05<00:00, 9820.80it/s] 


count     win    lose    draw
    1   29454   14352    6194
    2   14208   29592    6200
total   43662   43944   12394

ratio     win    lose    draw
    1   58.9%   28.7%   12.4%
    2   28.4%   59.2%   12.4%
total   43.7%   43.9%   12.4%

ai14s VS ai2


100%|██████████| 50000/50000 [00:24<00:00, 2030.51it/s]


count     win    lose    draw
    1   49446       0     554
    2   44043       0    5957
total   93489       0    6511

ratio     win    lose    draw
    1   98.9%    0.0%    1.1%
    2   88.1%    0.0%   11.9%
total   93.5%    0.0%    6.5%

ai_abs_dls
 48.9 ms ±   1.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



In [16]:
mb1 = Marubatsu(boardclass=NpBoard)
mb1.move(0, 0)
mb1.move(1, 0)
mb1.move(2, 0)
%timeit mb1.board.board_to_str()
mb2 = Marubatsu(boardclass=NpIntBoard)
mb2.move(0, 0)
mb2.move(1, 0)
mb2.move(2, 0)
%timeit mb2.board.board_to_str()


790 ns ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.46 μs ± 44.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
%timeit mb1.board.board == mb1.CIRCLE
%timeit mb2.board.board == mb2.CIRCLE


936 ns ± 18 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
822 ns ± 21.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
import numpy as np

%timeit np.full((10, 10), ".") == "."
%timeit np.full((10, 10), 0) == 0

3.53 μs ± 65.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.23 μs ± 98.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
